spring.application.name=acompaname-backend

# Conexión a la base de datos MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/acompaname_db
spring.datasource.username=acompaname_user
spring.datasource.password=acompaname_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API
api-endpoint=api/v1